version: '3.5'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    volumes:
      - type: volume
        source: venv
        target: /app/.venv
    ports:
      - '80:3002'
    env_file: .env

volumes:
  venv:
